### ISSUE TITLE
Is the recipe truly noarch: python?

### ISSUE THREAD

**Issue by rs2** [conda-forge/pytest-icdiff-feedstock#7]
The recipe declares itself as `noarch: python`, yet it constrains `python` to be 3.6 or better:
https://github.com/conda-forge/pytest-icdiff-feedstock/blob/8b238f63186df8a5c2d6559419de3896b980882d/recipe/meta.yaml#L13-L26

This sounds contradictory.

**Comment by nicoddemus** [comment]
That's correct, `noarch` just means it is platform independent, meaning it can run in Windows, Linux, etc, not that it runs in _any_ Python version (which is next to impossible, running in any Python version would mean running perhaps even in Python 2.0, which is not feasible).

More docs:
* https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=noarch#noarch-builds
* https://docs.anaconda.com/anaconda-repository/user-guide/tasks/pkgs/use-noarch-pkgs/

Cheers!
